sudo: false
dist: trusty
language: scala

scala:
- 2.12.10
- 2.13.1

jdk:
- oraclejdk8

cache:
  directories:
    - $HOME/.cache
    - $HOME/.ivy2/cache
    - $HOME/.sbt

script:
  - sbt ++$TRAVIS_SCALA_VERSION -Dsbt.supershell=false -Dsbt.log.noformat=true clean test