addSbtPlugin("com.eed3si9n"       % "sbt-unidoc"   % "0.4.1")
addSbtPlugin("com.geirsson"       % "sbt-scalafmt" % "1.6.0-RC4")
addSbtPlugin("com.jsuereth"       % "sbt-pgp"      % "1.1.2")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype" % "2.3")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"      % "0.3.7")
